### ISSUE TITLE
Allow delete from git repo

### ISSUE THREAD

**Issue by malmuzaini** [argoproj/gitops-engine#155]
Currently, I am using fluxcd for syncing our cluster from GitOps repo, which is a centralized repo for all of our services and infra tools manifests. And there is something I wish fluxcd offers which is deleting a resource from the GitOps repo would be reflected in the sync process. I don't have experience with ArgoCD, and I am not sure if it offers this. If it is then this would be fantastic if it's not then this space would be for discussing this. Now, when we delete any thing from the GitOps repo we have to delete it manually from the cluster. It's nuisance since sometimes or many times can be forgotten 😅. 

I am thinking to make it a feature switched by an annotation to have more controller over it. And I have an idea to implement it

**Comment by jannfis** [comment]
Hey, this feature exists and is called `pruning` in our terminology.

If you perform a sync with `pruning` enabled, resources that are deleted from Git (or more specific, those not contained in the final rendered manifests used as the reconciliation source) will also be deleted from the cluster. If the sync is performed with `pruning` disabled, those resources will be marked as "require pruning" to indicate that they are not existing in the manifests any more, so you can delete them manually if you wish to.

**Comment by malmuzaini** [comment]
Fantastic! I will close this then
