### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by alexmt** [argoproj/gitops-engine#158]
# Summary

We don't have a well-defined GitOps Engine release process. The library consumers use commit SHA instead of release tag. 

Referencing the commit in the main branch worked well since we rarely make big changes in GitOps engine and only consumer was Argo CD. However, this does not allow cherry-pick hot-fixes, into the previous release and the Argo CD is no longer the only consumer: https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent

# Proposal

Start creating release branches and tags:

* Instead of assuming that the main branch is 100% stable, create a release branches for every release. Release branches allow us to cherry-pick bug fixes into recent stable releases.
* Release branches namomg convention: `release-0.1`, `release-0.2` etc. 
* Release = release tag (`v0.1.1`, `v0.1.2`, `v0.2.0` etc) pointing to a commit existing in release branch.

**Additional notes**:

* Argo CD is the main source of new feature requests and we still heavily rely on Argo CD to test changes. To avoid overhead Argo CD dev/main branch is going to keep referencing commit SHA. So the release process won't change anything for Argo CD developers.

* Release frequency. Let's not create a separate release for every commit. With two consumers, we know when release is required so it can be done on demand.

* Argo CD release branch should reference GitOps Engien using release tag .

**Comment by ash2k** [comment]
This makes sense to me. I'd like to add that I don't mind breaking changes so if there is a need to change API or something like that, don't worry about the agent too much as long as there will still be a way to do the same thing. Also would be nice to get a heads up if there is a breaking change coming. Thanks!
