### ISSUE TITLE
Needs a cool new logo

### ISSUE THREAD

**Issue by igaskin** [argoproj/gitops-engine#17]
Every kube project needs a memorable logo.

**Comment by stefanprodan** [comment]
![](https://eks.handson.flagger.dev/cuddle_clap.gif)

**Comment by dholbach** [comment]
Maybe we should just do this one for now?

![Argo-Flux_logos](https://user-images.githubusercontent.com/1346979/68929755-405f6c00-078d-11ea-819a-2281237d9ba7.png)

**Comment by dholbach** [comment]
> Maybe we should just do this one for now?
> 
> ![Argo-Flux_logos](https://user-images.githubusercontent.com/1346979/68929755-405f6c00-078d-11ea-819a-2281237d9ba7.png)

This is on [our main README.md](https://github.com/argoproj/gitops-engine) now. Is this good enough for now?
