### ISSUE TITLE
Which of Flux or Argo will be more ease to migrate to GitOps Engine later

### ISSUE THREAD

**Issue by nielsonsantana** [argoproj/gitops-engine#28]
Hi guys. I saw that GitOps Engine will be the successor of Flux and Argo. 
My doubt is which (Flux or Argo) will be more ease to migrate to GitOps Engine later.

**Comment by alexmt** [comment]
Hello @nielsonsantana ,

As of now, GitOps engine is a library, not a product for end-user. The goal is to re-use it in both Argo CD and Flux. There is no plan to change user experience in either of the projects yet. 

Hopefully, It will make it easier to migrate from Flux to Argo CD or other way around.

**Comment by nielsonsantana** [comment]
Hi @alexmt,
Thanks for the explanation!! Before your explanation, wasn't clear which choose to go with.
