### ISSUE TITLE
Is this project still on?

### ISSUE THREAD

**Issue by vikas027** [argoproj/gitops-engine#30]
Just curious to know if you guys are still looking to join hands with [ArgoCD](https://argoproj.github.io/argo-cd/). This repo has not been updated for quite a few months.

**Comment by brunopadz** [comment]
I believe it is. It seems the team is facing some CNCF bureaucracy. Check #6 for more info.

**Comment by opensourceonly** [comment]
@alexmt Is this planned to be implemented as a replacement for Argo CD ?

**Comment by alexmt** [comment]
@opensourceonly , @vikas027 . Finally we've pushed real code into this repository. Argo CD core has been extracted into re-usable library that can be consumed by Flux or any other project. Argo CD master already uses it. 

![image](https://user-images.githubusercontent.com/426437/82109167-ca5ea200-96e8-11ea-8f65-62ad5f1ae89f.png)

Next step is documentation: https://github.com/argoproj/gitops-engine/issues/31

**Comment by alexmt** [comment]
Closing the ticket. Let me know please if you have more questions.
