### ISSUE TITLE
Upgrade to k8s 1.24

### ISSUE THREAD

**Issue by gusfcarvalho** [argoproj/gitops-engine#417]
Similarly to #364, I believe there are some incompatibility with gitops-engine and k8s 1.24 libraries: https://github.com/argoproj/gitops-engine/blob/master/pkg/utils/kube/resource_ops.go#L278 such as `DryRunVerifier` not being supported anymore.

I'm glad to take this issue if no one else can, but I'd need some input as I've never worked with these libraries before :).

**Comment by jannfis** [comment]
This apparently has been solved with https://github.com/argoproj/gitops-engine/pull/427
