### ISSUE TITLE
Outdated static `pkg/utils/kube/scheme/parser.go` causing `field not declared in schema` errors in ArgoCD

### ISSUE THREAD

**Issue by r0bobo** [argoproj/gitops-engine#558]
I've had two cases of sync errors in ArgoCD:

For `CSIDriver`:
```
Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: .spec.seLinuxMount: field not declared in schema
```

For `Pod` with [native sidecar containers](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) and the field `.spec.initContainers.restartPolicy`:
```
Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedConfig: errors: .spec.template.spec.initContainers[name="helper"].restart: field not declared in schema .spec.template.spec.initContainers[name="podman"].restart: field not declared in schema
```
After digging around in the code I think the problem might be that the static inlined schema [here](https://github.com/argoproj/gitops-engine/blob/master/pkg/utils/kube/scheme/parser.go) is outdated and is missing those fields.

[Here is a related ArgoCD issue](https://github.com/argoproj/argo-cd/issues/13585) for the `CSIDriver` problem.

Kubernetes version: v1.28.4 with the `SidecarContainers` feature gate enabled
ArgoCD version: v2.9.3

**Comment by adberger** [comment]
Any updates on this?

`seLinuxMount` is in the spec since kubernetes v1.25!

see:
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#csidriverspec-v1-storage-k8s-io
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#csidriverspec-v1-storage-k8s-io

**Comment by wpi86** [comment]
Hi, have similar issue, but with Jobs 
"error building typed results: error creating typedLive: errors: .spec.podReplacementPolicy: field not declared in schema."
JobPodReplacementPolicy featuregate now in beta and enabled by default.
eks 1.29 + argo v2.10.0+2175939

**Comment by Typositoire** [comment]
I'm also currently hitting this with Kyverno latest chart and multiple fields, the only way to make the chart compute without having `Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: XYZ: field not declared in schema` is to ignore them like so.

```
ignoreDifferences:
  - group: kyverno.io
    kind: ClusterPolicy
    jqPathExpressions:
      - .status.validatingadmissionpolicy
      - .status.autogen
      - '.spec.rules[].skipBackgroundRequests'
      - .spec.admission
```

**Comment by kamelj** [comment]
Hello @wpi86 
I have the same issue here, What did you do regarding your error "errors: .spec.podReplacementPolicy: field not declared in schema"?


> Hi, have similar issue, but with Jobs "error building typed results: error creating typedLive: errors: .spec.podReplacementPolicy: field not declared in schema." JobPodReplacementPolicy featuregate now in beta and enabled by default. eks 1.29 + argo v2.10.0+2175939

**Comment by wpi86** [comment]
> Hello @wpi86 I have the same issue here, What did you do regarding your error "errors: .spec.podReplacementPolicy: field not declared in schema"?
> 
> > Hi, have similar issue, but with Jobs "error building typed results: error creating typedLive: errors: .spec.podReplacementPolicy: field not declared in schema." JobPodReplacementPolicy featuregate now in beta and enabled by default. eks 1.29 + argo v2.10.0+2175939

Hi, currently we keep our jobs as argo hooks, in this case argo doesn't try to validate them on sync and it works

**Comment by martijnvdp** [comment]
think i got the same issue with the latest gatekeeper release i got this error even the field is in the scheme

`Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedConfig: .webhooks[name="validation.gatekeeper.sh"].matchConditions: field not declared in schema`

**Comment by martijnvdp** [comment]
think i got the same issue with the latest gatekeeper release i got this error even the field is in the scheme k8s 1.28+

helm:
```
kind: ValidatingWebhookConfiguration
  {{- if ge (int .Capabilities.KubeVersion.Minor) 28 }}
  matchConditions: {{ toYaml .Values.validatingWebhookMatchConditions | nindent 4 }}
  {{- end }}
```


`Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedConfig: .webhooks[name="validation.gatekeeper.sh"].matchConditions: field not declared in schema`

**Comment by ptr1120** [comment]
I also have a problem with a simple job that breaks the complete deployment.
```
Sync operation to 3a93a6cc5f459e30b53659ffcd0b8fc9e5df2acb failed: ComparisonError: Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: errors:
  .spec.podReplacementPolicy: field not declared in schema
  .status.terminating: field not declared in schema
```

I tried to fix it with

```yaml
  ignoreDifferences:
    - kind: Job
      jqPathExpressions:
        - .spec.podReplacementPolicy
        - .status.terminating
```

without success. 

Any idea?

**Comment by wpi86** [comment]
> I also have a problem with a simple job that breaks the complete deployment.
> 
> ```
> Sync operation to 3a93a6cc5f459e30b53659ffcd0b8fc9e5df2acb failed: ComparisonError: Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: errors:
>   .spec.podReplacementPolicy: field not declared in schema
>   .status.terminating: field not declared in schema
> ```
> 
> I tried to fix it with
> 
> ```yaml
>   ignoreDifferences:
>     - kind: Job
>       jqPathExpressions:
>         - .spec.podReplacementPolicy
>         - .status.terminating
> ```
> 
> without success.
> 
> Any idea?

Argo has released a new version that knows this field, the update solved our problem

**Comment by ptr1120** [comment]
@wpi86 thank you, but updating argocd to v2.12.0-rc1 for me does not solve the problem with the job, maybe it's additionally due to using server-side-apply (https://github.com/argoproj/argo-cd/issues/17358)

```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .spec.podReplacementPolicy: field not declared in schema
```

**Comment by ptr1120** [comment]
The only difference I notice is ignoring field managers in argocd-cm produces 2 errors (`spec.podReplacementPolicy`, `status.terminating`):

```
Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: errors: .status.terminating: field not declared in schema .spec.podReplacementPolicy: field not declared in schema
```

Removing the filed managers ignore rules from argocd-cd produces 1 error (`podReplacementPolicy`):
```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from live resource: .spec.podReplacementPolicy: field not declared in schema
```

**Comment by stongo** [comment]
I'm having the same problem with other fields.
Another workaround is to disable validation completely in the sync policy.
```
syncOptions:
- Validate=false
```

**Comment by dwilliams782** [comment]
Should be fixed by: https://github.com/argoproj/gitops-engine/pull/588

**Comment by crenshaw-dev** [comment]
I've updated the static schema to 0.29. Please try Argo CD 2.12.0-rc3. https://github.com/argoproj/gitops-engine/pull/588
