### ISSUE TITLE
SyncContext deletes in progress resources on termination

### ISSUE THREAD

**Issue by ash2k** [argoproj/gitops-engine#79]
https://github.com/argoproj/gitops-engine/blob/ff6e9f853241994e4e9ac9346fe4d22bab6d55e6/pkg/sync/sync_context.go#L649-L648

I'm not sure if this is intended but it looks like it may be causing deletions of resources that are being updated. E.g. if a `Deployment` is being updated to roll out a new version of an image and the sync context is terminated, it will be deleted.

Behavior on termination should probably be configurable. Off the top of my head, options are:
- Don't do anything, just stop doing whatever it's doing.
- Roll things back. Delete created objects, undo changes to updated objects.

I might have misunderstood the code, I'm sorry if that's the case.

**Comment by alexmt** [comment]
Hello @ash2k ,

Only "in-flight" sync hooks are supposed to be deleted if sync operation is terminated. I think non-hooks are skipped by the check at line 640: https://github.com/argoproj/gitops-engine/blob/ff6e9f853241994e4e9ac9346fe4d22bab6d55e6/pkg/sync/sync_context.go#L640

This behavior was introduced in [v1.4](https://argoproj.github.io/argo-cd/operator-manual/upgrading/1.3-1.4/) release. Typically resources such as Deployments, StatefulSets are not supposed to be used as hooks and instead we suggest to use Sync Waves.

**Comment by ash2k** [comment]
Thanks for clarifying it!
